// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNxXmnMBrtIvsEKblpfE5sAzlTGjlthdg',
    appId: '1:621593622925:web:7757da3fc79812e303a5c4',
    messagingSenderId: '621593622925',
    projectId: 'incio-sesion-22',
    authDomain: 'incio-sesion-22.firebaseapp.com',
    storageBucket: 'incio-sesion-22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyxTGQvGxjrR7RpDWbNkzcowxWqSjxBDA',
    appId: '1:621593622925:android:ffe44c24fb7b558703a5c4',
    messagingSenderId: '621593622925',
    projectId: 'incio-sesion-22',
    storageBucket: 'incio-sesion-22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzzBU5XpyGm-dZaTIcyrqX34k_KwK3KPI',
    appId: '1:621593622925:ios:a4c78a09da802bdd03a5c4',
    messagingSenderId: '621593622925',
    projectId: 'incio-sesion-22',
    storageBucket: 'incio-sesion-22.appspot.com',
    iosClientId: '621593622925-g1lui1o0608r5pai3vnnndc9iiesh63a.apps.googleusercontent.com',
    iosBundleId: 'com.example.joinV2',
  );
}
